#! /bin/bash

PUPPET_ENV=production
PUPPET_ENVDIR=/etc/puppetlabs/code/environments/${PUPPET_ENV}

[ $(id -u) -ne 0 ] && {
  echo Re-running with sudo >&2
  exec sudo $0 $*
}

echo $PATH | grep -q /opt/puppetlabs/bin || PATH=${PATH}:/opt/puppetlabs/bin
echo $PATH | grep -q /opt/puppetlabs/puppet/bin || PATH=${PATH}:/opt/puppetlabs/puppet/bin

cd ${PUPPET_ENVDIR}

#
# run librarian-puppet to install initial modules
#

[ ${LANG:-C} == "C" ] && LANG=en_US.UTF-8
[ ${LC_ALL:-C} == "C" ] && LC_ALL=en_US.UTF-8

librarian-puppet update

puppet apply --verbose \
             --detailed-exitcodes \
             --environment=${PUPPET_ENV} \
             --modulepath=${PUPPET_ENVDIR}/modules \
             $* \
             ${PUPPET_ENVDIR}/manifests/site.pp

