#! /bin/bash

puppet_version=5.5.0-1

HERE=`cd $(dirname $0); pwd -P`
cd ${HERE}

mode=download

[ "${1}" == download ] && shift

if [ $# -eq 0 ]; then

  [ $(id -u) -ge 500 ] || {
    echo Please run as the primary user of this system, not root >&2
    exit 1
  }

  type -p sw_vers >/dev/null 2>&1 || {
    echo "Failed to find sw_vers - are you sure this is a Mac?" >&2
    exit 1
  }

  sw_vers -productName | grep -q '^Mac OS X$' || {
    echo "This is not a Mac" >&2
    exit 1
  }

elif [ $# -eq 2 ]; then

  [ "${1}" == install ] || {
    echo Unknown mode: $1 >&2
    exit 1
  }

  mode=$1
  user=$2

  [ $(id -u) -eq 0 ] || {
    echo Sudo failed, please try again >&2
    exit 1
  }

else
  echo Usage: $(basename $0) >&2
  exit 1
fi

product_version=$(sw_vers -productVersion)
major_version=${product_version%.*}
machine_hw=$(uname -m)

if [ $mode == download ]; then

  DMG_URL=https://downloads.puppetlabs.com/mac/puppet5/${major_version}/${machine_hw}/puppet-agent-${puppet_version}.osx${major_version}.dmg

  curl -o puppet.dmg ${DMG_URL}

  sudo $0 install $(id -un)

  brew doctor

else

  volume=$(hdiutil mount ${HERE}/puppet.dmg | awk '/\/Volumes\/puppet/ {print $3}')
  installer -pkg ${volume}/puppet-agent-*-installer.pkg -target /
  hdiutil unmount ${volume}
  rm -f puppet.dmg

  #
  # sometimes the permissions on /usr/local/lib/pkgconfig are wrong,
  # so create it first and fix its permissions
  #
  mkdir -p /usr/local/lib/pkgconfig
  chown -R ${user}:admin /usr/local/lib

  #
  # replace production environment dir with link to the puppet subdir here
  #
  ENV_DIR=/etc/puppetlabs/code/environments/
  rm -rf ${ENV_DIR}/production
  ln -s ${HERE}/puppet ${ENV_DIR}/production

  #
  # install librarian-puppet
  #
  PUPPET_BIN=/opt/puppetlabs/puppet/bin
  ${PUPPET_BIN}/gem install -N librarian-puppet

  #
  # Add extra paths
  #
  echo /usr/local/bin   > /etc/paths.d/mcgonagle
  echo /usr/local/sbin >> /etc/paths.d/mcgonagle

  #
  # add the puppet dirs to PATH
  #
  PATH=${PATH}:/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin

  cd puppet 

  #
  # homebrew user setting
  #

  cat >data/user.yaml <<USERYAML
# Homebrew user settings
# *** automatically generated -- do not edit ***
---
homebrew::user: ${user}
homebrew::group: admin
homebrew::multiuser: true
USERYAML
  
  #
  # run librarian-puppet to install initial modules
  #
  librarian-puppet install

  cd ..

  ./apply

fi


