#! /bin/bash

if [ $(id -u) -eq 0 ]; then
  echo Please run as the primary user of this system, not root >&2
  exit 1
fi

PUPPET_DIR=opt/puppetlabs
PUPPET_ETC=private

sudo puppet resource service puppet ensure=stopped enable=false
sudo puppet resource service mcollective ensure=stopped enable=false
sudo puppet resource service pxp-agent ensure=stopped enable=false

cd /
pkgutil --only-files --files com.puppetlabs.puppet-agent |\
  egrep -v '^(opt/puppetlabs|private/etc/puppetlabs)' |\
  sudo xargs rm -f

sudo rm -rf opt/puppetlabs private/etc/puppetlabs

sudo pkgutil --forget com.puppetlabs.puppet-agent

BREW_CACHE=$(brew --cache)

#
# uninstall homebrew
#
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

echo You should remove the ${BREW_CACHE} directory
