#! /bin/bash

if [ $(id -u) -eq 0 ]; then
  echo Please run as the primary user of this system, not root >&2
  exit 1
fi

PUPPET_DIR=opt/puppetlabs
PUPPET_ETC=private/etc/puppetlabs
PUPPET=/${PUPPET_DIR}/bin/puppet

cd /

if [ -d ${PUPPET_DIR} -a -d ${PUPPET_ETC} -a -x ${PUPPET} ]; then

  for svc in puppet mcollective pxp-agentl; do
    sudo ${PUPPET} resource service ${svc} ensure=stopped enable=false
  done


  pkgutil --only-files --files com.puppetlabs.puppet-agent |\
    egrep -v "^(${PUPPET_DIR}|${PUPPET_ETC})" |\
    sudo xargs rm -f

  sudo rm -rf ${PUPPET_DIR} ${PUPPET_ETC}

  sudo pkgutil --forget com.puppetlabs.puppet-agent

fi

if [ -x /usr/local/bin/brew ]; then
  #
  # uninstall homebrew
  #
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
fi

