#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# shortcut for a module from a generic git repo
def gitrepo(repo, name, ref = 'master')
  mod name.split('/').join('-'),
      :git => "https://#{repo}/#{name}.git",
      :ref => ref
end

# shortcut for a module from GitHub
def github(name, ref = 'master')
  gitrepo "github.com", name, ref
end

# shortcut for a module from code.stanford.edu
def stanford(name, ref = 'master')
  gitrepo "code.stanford.edu", name, ref
end

# shortcut for a module under development
def dev(name, *args)
  mod "puppet-#{name}", :path => "#{ENV['HOME']}/src/puppet/modules/#{name}"
end

# required modules
mod 'thekevjames-homebrew', '1.8.0'
mod 'binford2k-mas', '0.0.2'
